class CfgVehicles
{
	class USP_45L_RUCKSACK;
	class USP_45L_RUCKSACK_GRN;
	class USP_45L_RUCKSACK_TAN;
	class USP_45L_RUCKSACK_MC;
	class USP_45L_RUCKSACK_MCD;

	class USP_DELTA_BAG_BLK;
	class USP_DELTA_BAG_AOR1;
	class USP_DELTA_BAG_AOR2;
	class USP_DELTA_BAG_CBR;
	class USP_DELTA_BAG_GRY;
	class USP_DELTA_BAG_RGR;
	class USP_DELTA_BAG_MC;
	class USP_DELTA_BAG_MCA;
	class USP_DELTA_BAG_MCB;
	class USP_DELTA_BAG_MCD;
	class USP_DELTA_BAG_MCT;
	class USP_DELTA_BAG_M81;

	class USP_HYDRATION_PACK_CBR;
	class USP_HYDRATION_PACK_GRY;
	class USP_HYDRATION_PACK_RGR;
	class USP_HYDRATION_PACK_MC;
	class USP_HYDRATION_PACK_MCA;
	class USP_HYDRATION_PACK_MCB;
	class USP_HYDRATION_PACK_MCD;
	class USP_HYDRATION_PACK_MCT;
	class USP_HYDRATION_PACK_AOR1;
	class USP_HYDRATION_PACK_AOR2;
	class USP_HYDRATION_PACK_3CD;
	class USP_HYDRATION_PACK_M81;

	class USP_HYDROPACK_CBR;
	class USP_HYDROPACK_GRY;
	class USP_HYDROPACK_RGR;
	class USP_HYDROPACK_MC;

	class USP_MEDIUM_PACK_CBR;
	class USP_MEDIUM_PACK_RGR;

	class USP_MOAB_RUSH_RGR;
	class USP_MOAB_RUSH_TAN;

	class USP_PACK_BREACHER_CBR;
	class USP_PACK_BREACHER_RGR;
	class USP_PACK_BREACHER_MC;

	class USP_PATROL_PACK_CB;
	class USP_PATROL_PACK_CB_CS;
	#include "cfg\backpacks.hpp"
	#include "cfg\units.hpp"
};
